---
- name: php repository gpg key (stretch only)
  become: yes
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when: raspbian_version.stdout == 'stretch'

- name: php repository (stretch only)
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    filename: php7.list
    state: present
  when: raspbian_version.stdout == 'stretch'

- name: install nginx
  become: yes
  apt:
    update_cache: no
    state: present
    name: nginx

- name: install php
  become: yes
  apt:
    update_cache: no
    state: present
    name:
      - php7.2-fpm
      - php7.2-mbstring
      - php7.2-sqlite3

- name: install composer
  become: yes
  apt:
    update_cache: no
    state: present
    name: composer

- name: add pi user to www-data group
  become: yes
  user:
    name: pi
    groups: www-data
    append: yes

- name: web directory
  become: yes
  file:
    path: "{{ web_home }}"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: config directory
  become: yes
  file:
    path: "{{ web_home }}/Config"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: php config file
  become: yes
  template:
    src: Config.php.j2
    dest: "{{ web_home }}/Config/Config.php"
    owner: pi
    group: www-data
    mode: 0644

- name: nginx config file
  become: yes
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: update images directory group
  become: yes
  file:
    path: "{{ images_output }}"
    state: directory
    group: www-data

- name: update thumbnails directory group
  become: yes
  file:
    path: "{{ images_output }}/thumb"
    state: directory
    group: www-data

- name: update database folder permissions
  become: yes
  file:
    path: "{{ noaa_home }}/db"
    group: www-data
    mode: 0770

- name: update database file permissions
  become: yes
  file:
    path: "{{ noaa_home }}/db/panel.db"
    group: www-data
    mode: 0770
...
