---
- name: noaa environment variables
  template:
    src: noaa-v2.conf.j2
    dest: ~pi/.noaa-v2.conf
    owner: pi
    group: pi
    mode: 0644

- name: predict directory
  file:
    path: ~pi/.predict
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: predict config file
  template:
    src: predict.qth.j2
    dest: ~pi/.predict/predict.qth
    owner: pi
    group: pi
    mode: 0644

- name: wxtoimg config file
  template:
    src: wxtoimgrc.j2
    dest: ~pi/.wxtoimgrc
    owner: pi
    group: pi
    mode: 0644

- name: wxtoimg license terms acceptance file
  copy:
    src: wxtoimglic
    dest: ~pi/.wxtoimglic
    owner: pi
    group: pi
    mode: 0644

- name: log directory for rspi-noaa-ham logs
  become: yes
  file:
    path: /var/log/rspi-noaa-ham
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: logrotate settings for rspi-noaa-ham logs
  become: yes
  copy:
    src: logrotate-settings
    dest: /etc/logrotate.d/rspi-noaa-ham
    owner: root
    group: root
    mode: 0644

- name: gnuradio home directory
  file:
    path: ~pi/.gnuradio
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: gnuradio prefs directory
  file:
    path: ~pi/.gnuradio/prefs
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: gnuradio prefs file
  copy:
    src: vmcircbuf_default_factory
    dest: ~pi/.gnuradio/prefs/vmcircbuf_default_factory
    owner: pi
    group: pi
    mode: 0644

- name: disable wifi power mgmt script
  become: yes
  copy:
    src: disable-wifi-powermgmt.sh
    dest: /usr/local/sbin/disable-wifi-powermgmt.sh
    owner: root
    group: root
    mode: 0755
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_script

- name: disable wifi power mgmt service definition
  become: yes
  copy:
    src: disable-wifi-powermgmt.service
    dest: /lib/systemd/system/disable-wifi-powermgmt.service
    owner: root
    group: root
    mode: 0644
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_service

- name: enable systemd wifi power management disable service
  become: yes
  systemd:
    daemon_reload: yes
    name: disable-wifi-powermgmt.service
    enabled: yes
  when: (wifi_powermgmt_script.changed or wifi_powermgmt_service.changed) and (disable_wifi_power_mgmt|bool)

- name: annotation directory
  file:
    path: ~pi/config/annotation
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: annotation file (sample for modification)
  copy:
    src: annotation.html.j2_file
    dest: ~pi/rspi-noaa-ham/config/annotation/annotation.html.j2
    force: no
    owner: pi
    group: pi
    mode: 0600

- name: annotation file image (sample for modification)
  copy:
    src: rspi-noaa-ham-logo.png
    dest: ~pi/rspi-noaa-ham/config/annotation/rspi-noaa-ham-logo.png
    force: no
    owner: pi
    group: pi
    mode: 0600
...
