---
- name: install raspberry-noaa-v2 webpanel
  hosts: webserver
  connection: local
  gather_facts: no
  roles:
    - role: webserver
  post_tasks:
    - name: output web server url
      debug:
        msg: "Your web server URL is: http://<hostname_or_ip>:{{ web_port }}"
...
